### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Shiv-Patil**
- Fix username xss #14 
- Fix "Yesterday" date-time format
- Fix thumbnail size
- **changed font family** @MrBlueBird2

### CODE REVIEW

**Comment by MrBlueBird2** [comment]
Okay bruh

**Comment by MrBlueBird2** [comment]
But which font family btw?

**Comment by MrBlueBird2** [comment]
Oh Inter okay then

**Review by aadtyn — APPROVED** [review]
good shit dude

#14 fixed

**Comment by MrBlueBird2** [comment]
Soul merge asap

**Comment by MrBlueBird2** [comment]
Soul merge asap

**Pull request merged**
